site_name: CIRCexplorer2
repo_url: https://github.com/YangLab/CIRCexplorer2
site_description: Documents for CIRCexplorer2
site_author: Xiao-Ou Zhang
copyright: Copyright (C) 2016-2017 YangLab
pages:
    - Home: 'index.md'
    - Tutorial:
        - 'Installation and Setup': 'tutorial/setup.md'
        - 'Pipeline': 'tutorial/pipeline.md'
        - 'Alignment': 'tutorial/alignment.md'
        - 'Parsing': 'tutorial/parsing.md'
        - 'Annotating': 'tutorial/annotating.md'
        - 'Assembly': 'tutorial/assembly.md'
        - 'Alternative Splicing': 'tutorial/as.md'
        - 'Run CIRCexplorer2 via One Command': tutorial/one_step.md
    - Modules:
        - 'Align': 'modules/align.md'
        - 'Parse': 'modules/parse.md'
        - 'Annotate': 'modules/annotate.md'
        - 'Assemble': 'modules/assemble.md'
        - 'Denovo': 'modules/denovo.md'
    - About:
        - 'Related Tools': 'about/tools.md'
        - 'FAQ': 'about/faq.md'
        - 'Release Notes': 'about/changelog.md'
        - 'License': 'about/license.md'
theme: 'readthedocs'
